CREATE TABLE jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users NOT NULL,
  platform TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'APPLIED',
  company_name TEXT NOT NULL,
  position_title TEXT NOT NULL,
  origin_url TEXT,
  raw_data JSONB,
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own jobs" 
ON jobs FOR ALL 
USING (auth.uid() = user_id);

CREATE TABLE memos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID REFERENCES jobs(id) ON DELETE CASCADE,
  content TEXT,
  is_draft BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE memos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage memos of their own jobs"
ON memos FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM jobs 
    WHERE jobs.id = memos.job_id 
    AND jobs.user_id = auth.uid()
  )
);