
CREATE TYPE job_platform AS ENUM ('WANTED', 'SARAMIN', 'LINKEDIN', 'MANUAL');
CREATE TYPE job_status AS ENUM ('APPLIED', 'DOCS_PASSED', 'INTERVIEWING', 'OFFERED', 'REJECTED');

CREATE TABLE jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users NOT NULL,
  platform job_platform NOT NULL, 
  status job_status NOT NULL DEFAULT 'APPLIED',
  company_name TEXT NOT NULL,
  position_title TEXT NOT NULL,
  origin_url TEXT,
  raw_data JSONB,
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_jobs_user_id ON jobs(user_id);

CREATE TABLE memos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID REFERENCES jobs(id) ON DELETE CASCADE,
  content TEXT,
  is_draft BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_memos_updated_at
    BEFORE UPDATE ON memos
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own jobs" ON jobs FOR ALL USING (auth.uid() = user_id);

ALTER TABLE memos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage memos of their own jobs" ON memos FOR ALL USING (
  EXISTS (SELECT 1 FROM jobs WHERE jobs.id = memos.job_id AND jobs.user_id = auth.uid())
);